name       : veracrypt
version    : '1.24_3'
release    : 12
source     :
    - https://launchpad.net/veracrypt/trunk/1.24-update3/+download/VeraCrypt_1.24-Update3_Source.tar.bz2 : 0c28fab15a9d051e372bf14f5f580b65b15394b9462dbf887f26776e66eaa90a
license    :
    - TrueCrypt-3.0
    - Apache-2.0
component  : security.crypto
summary    : Disk encryption software based on TrueCrypt
description: Disk encryption software based on TrueCrypt
builddeps  :
    - pkgconfig(fuse)
    - wxwidgets-devel
    - yasm
build      : |
    %make -C src \
        TC_EXTRA_CFLAGS="${CFLAGS}" \
        TC_EXTRA_CXXFLAGS="${CXXFLAGS}" \
        TC_EXTRA_LFLAGS+="-ldl ${LDFLAGS}"
install    : |
    install -Dm00755 src/Main/veracrypt $installdir/usr/bin/veracrypt
    install -Dm00644 src/Resources/Icons/VeraCrypt-256x256.xpm $installdir/usr/share/pixmaps/veracrypt.xpm
    install -Dm00644 $pkgfiles/veracrypt.desktop $installdir/usr/share/applications/veracrypt.desktop
