name       : veracrypt
version    : 1.25.9
release    : 19
source     :
    - https://launchpad.net/veracrypt/trunk/1.25.9/+download/VeraCrypt_1.25.9_Source.tar.bz2 : 76b6e18184bc21a41d2949ff63d721d49054a716ceff3a4bd77b5c3510b794af
license    :
    - TrueCrypt-3.0
    - Apache-2.0
component  : security.crypto
summary    : Disk encryption software based on TrueCrypt
description: Disk encryption software based on TrueCrypt
builddeps  :
    - pkgconfig(fuse)
    - wxwidgets-devel
    - yasm
build      : |
    %make -C src \
        TC_EXTRA_CFLAGS="${CFLAGS}" \
        TC_EXTRA_CXXFLAGS="${CXXFLAGS}" \
        TC_EXTRA_LFLAGS+="-ldl ${LDFLAGS}"
install    : |
    install -Dm00755 src/Main/veracrypt $installdir/usr/bin/veracrypt
    install -Dm00644 src/Resources/Icons/VeraCrypt-256x256.xpm $installdir/usr/share/pixmaps/veracrypt.xpm
    install -Dm00644 $pkgfiles/veracrypt.desktop $installdir/usr/share/applications/veracrypt.desktop
