name       : veracrypt
version    : 1.19
release    : 3
source     :
    - https://github.com/veracrypt/VeraCrypt/archive/VeraCrypt_1.19.tar.gz : 7d3fa5007b8e9dc93691c2da78dee497954b0596763a50e21724ec0564eb761b
license    :
    - TrueCrypt-3.0
    - Apache-2.0
component  : security.crypto
summary    : Disk encryption software based on TrueCrypt
description: Disk encryption software based on TrueCrypt
setup      : |
    %patch -p1 < $pkgfiles/no-makeself.patch
builddeps  :
    - pkgconfig(fuse)
    - wxwidgets-devel
build      : |
    cd src
    %make
install    : |
    install -Dm755 $workdir/src/Main/veracrypt $installdir/usr/bin/veracrypt
    install -Dm644 $workdir/src/Resources/Icons/VeraCrypt-256x256.xpm $installdir/usr/share/pixmaps/veracrypt.xpm
    install -Dm644 $pkgfiles/veracrypt.desktop $installdir/usr/share/applications/veracrypt.desktop
