name       : veracrypt
version    : '1.24'
release    : 10
source     :
    - https://launchpad.net/veracrypt/trunk/1.24/+download/VeraCrypt_1.24_Source.tar.bz2 : 23a66eee2438b98c05fc9254ec31fdf9d0266fa37ecc8a105e6b1d95a43b64cf
license    :
    - TrueCrypt-3.0
    - Apache-2.0
component  : security.crypto
summary    : Disk encryption software based on TrueCrypt
description: Disk encryption software based on TrueCrypt
builddeps  :
    - pkgconfig(fuse)
    - wxwidgets-devel
    - yasm
build      : |
    %make -C src \
        TC_EXTRA_CFLAGS="${CFLAGS}" \
        TC_EXTRA_CXXFLAGS="${CXXFLAGS}" \
        TC_EXTRA_LFLAGS+="-ldl ${LDFLAGS}"
install    : |
    install -Dm00755 src/Main/veracrypt $installdir/usr/bin/veracrypt
    install -Dm00644 src/Resources/Icons/VeraCrypt-256x256.xpm $installdir/usr/share/pixmaps/veracrypt.xpm
    install -Dm00644 $pkgfiles/veracrypt.desktop $installdir/usr/share/applications/veracrypt.desktop
